# Generated by Django 5.1.5 on 2025-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
