# Generated by Django 5.1.5 on 2025-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_student_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20)),
                ('publications', models.ManyToManyField(to='tables.publication')),
            ],
        ),
    ]
